//COMMON
export const FETCH_START = 'fetch_start';
export const FETCH_SUCCESS = 'fetch_success';
export const FETCH_ERROR = 'fetch_error';
export const SHOW_MESSAGE = 'SHOW_MESSAGE';
export const HIDE_MESSAGE = 'HIDE_MESSAGE';
export const ROUTES_LIST = 'ROUTES_LIST';

//AUTH
export const SIGNIN_USER = 'SIGNIN_USER';
export const SIGNIN_USER_SUCCESS = 'SIGNIN_USER_SUCCESS';
export const SIGNOUT_USER = 'SIGNOUT_USER';
export const SIGNOUT_USER_SUCCESS = 'SIGNOUT_USER_SUCCESS';
export const INIT_URL = 'INIT_URL';
export const USER_DATA = 'user_data';
export const USER_TOKEN_SET = 'user_token_set';
export const USER_UPDATE_PASSWORD = 'USER_UPDATE_PASSWORD';
export const PASSWORD_REQUIREMENTS = 'PASSWORD_REQUIREMENTS';
export const AUTH_MESSAGE = 'AUTH_MESSAGE';
export const AUTH_STATUS_ACTIONS = 'AUTH_STATUS_ACTIONS';
export const POWERBI_CHECK = 'POWERBI_CHECK';

//FIREBASE
export const NOTIFICATIONS_LIST = 'NOTIFICATIONS_LIST';
export const LOADED_OLD_NOTIFICATIONS = 'LOADED_OLD_NOTIFICATIONS';

//COLABORADOR
export const LIST_WORKER = "LIST_WORKER";
export const SAVE_WORKER = "SAVE_WORKER";
export const WORKER_STATUS_ACTIONS = "WORKER_STATUS_ACTIONS";
export const ACTIVE_WORKER = "ACTIVE_WORKER";
export const UPDATE_WORKER = "UPDATE_WORKER";
export const GET_WORKER = "GET_WORKER";
export const RESET_PASSWORD_WORKER = "RESET_PASSWORD_WORKER";
export const FILTER_WORKER = "FILTER_WORKER";

//ASISTENCIA
export const LIST_ASSISTANCE_BY_WORKER = "LIST_ASSISTANCE_BY_WORKER";
export const LIST_ASSISTANCE_ALL = "LIST_ASSISTANCE_ALL";
export const LIST_ASSISTANCE = "LIST_ASSISTANCE";
export const SAVE_ASSISTANCE = "SAVE_ASSISTANCE";
export const MY_ASSISTANCE = "MY_ASSISTANCE";
export const MY_ASSISTANCE_DETAIL = "MY_ASSISTANCE_DETAIL";
export const INDICATORS_ASSISTANCE = "INDICATORS_ASSISTANCE";
export const INDICATORS_ASSISTANCE_ALL = "INDICATORS_ASSISTANCE_ALL";
export const MY_TODAY_ASSISTANCE = "MY_TODAY_ASSISTANCE";
export const ASSISTANCE_STATUS_ACTIONS = "ASSISTANCE_STATUS_ACTIONS";
export const SAVE_ASSISTANCE_JUSTIFICATION = "SAVE_ASSISTANCE_JUSTIFICATION";

//ASOCIADO
export const LIST_ASSOCIATED = "LIST_ASSOCIATED";
export const FILTER_ASSOCIATED = "FILTER_ASSOCIATED";
export const INDICATORS_ASSOCIATED = "INDICATORS_ASSOCIATED";
export const ASSOCIATED_STATUS_ACTIONS = "ASSOCIATED_STATUS_ACTIONS";
export const SHOW_ASSOCIATED = "SHOW_ASSOCIATED";
export const SHOW_EDIT_ASSOCIATED = "SHOW_EDIT_ASSOCIATED";
export const UPDATE_ASSOCIATED = "UPDATE_ASSOCIATED";

//ASOCIADO
export const FILTER_DEBCOLLECTOR = "FILTER_DEBCOLLECTOR";
export const SAVE_ASSOCIATED = "SAVE_ASSOCIATED";
export const SHOW_RUC_SEARCHED = "SHOW_RUC_SEARCHED";
export const SHOW_DNI_SEARCHED = "SHOW_DNI_SEARCHED";

//LLAMADA
export const LIST_CALLS = "LIST_CALLS";
export const SAVE_CALL = "SAVE_CALL";
export const CALLS_STATUS_ACTIONS = "CALLS_STATUS_ACTIONS";

//CUENTA
export const SHOW_COMPROBANTE = "SHOW_COMPROBANTE";
export const LIST_BILLS = "LIST_BILLS";
export const LIST_BILLS_BY_SECTOR = "LIST_BILLS_BY_SECTOR";
export const INDICATORS_BILLS = "INDICATORS_BILLS";
export const LIST_PENDINGS = "LIST_PENDINGS";
export const INDICATORS_PENDINGS = "INDICATORS_PENDINGS";
export const LIST_MEMBERSHIPS = "LIST_MEMBERSHIPS";
export const BILL_STATUS_ACTIONS = "BILL_STATUS_ACTIONS";
export const SAVE_BILL = "SAVE_BILL";
export const PAY_BILL = "PAY_BILL";
export const ANUL_BILL = "ANUL_BILL";
export const LIST_REPEATED = "LIST_REPEATED";
export const BILL_DASHBOARD_DATA = "BILL_DASHBOARD_DATA";

//PROMOTOR
export const FILTER_PROMOTOR = "FILTER_PROMOTOR";

//COMITE GREMIAL
export const FILTER_COMITE = "FILTER_COMITE";

//LLAMADA
export const LIST_SERVICES = "LIST_SERVICES";
export const SAVE_SERVICE = "SAVE_SERVICE";
export const SERVICES_STATUS_ACTIONS = "SERVICES_STATUS_ACTIONS";

//CLIENTE
export const LIST_CLIENTS = "LIST_CLIENTS";
export const FILTER_CLIENTE = "FILTER_CLIENTE";
export const SAVE_CLIENT = "SAVE_CLIENT";
export const CLIENT_STATUS_ACTIONS = "CLIENT_STATUS_ACTIONS";

//CONCEPTO
export const FILTER_CONCEPT = "FILTER_CONCEPT";
export const SHOW_CLIENTE = "SHOW_CLIENTE";
export const LIST_CONCEPTO = "LIST_CONCEPTO";
export const SAVE_CONCEPT = "SAVE_CONCEPT";
export const UPDATE_CONCEPT = "UPDATE_CONCEPT";
export const CONCEPT_STATUS_ACTIONS = "CONCEPT_STATUS_ACTIONS";
export const GET_CONCEPT = "GET_CONCEPT";
export const FILTER_AREAS = "FILTER_AREAS";
export const FILTER_CATEGORIES = "FILTER_CATEGORIES";

//CAJA
export const LIST_BILLS_CAJA = "LIST_BILLS_CAJA";
export const INDICATORS_BILLS_CAJA = "INDICATORS_BILLS_CAJA";
export const DASHBOARD_DATA = "DASHBOARD_DATA";

//FORMALIZACION
//CURSO
export const LIST_CURSOS = "LIST_CURSOS";
export const GET_CURSO = "GET_CURSO";
export const SAVE_CURSO = "SAVE_CURSO";
export const UPDATE_CURSO = "UPDATE_CURSO";
export const CURSOS_STATUS_ACTIONS = "CURSOS_STATUS_ACTIONS";
export const FILTER_CURSOS = "FILTER_CURSOS";

//PARTICIPANTE
export const LIST_PARTICIPANTES = "LIST_PARTICIPANTES";
export const GET_PARTICIPANTE = "GET_PARTICIPANTE";
export const SAVE_PARTICIPANTE = "SAVE_PARTICIPANTE";
export const UPDATE_PARTICIPANTE = "UPDATE_PARTICIPANTE";
export const PARTICIPANTES_STATUS_ACTIONS = "PARTICIPANTES_STATUS_ACTIONS";
export const FILTER_PARTICIPANTS = "FILTER_PARTICIPANTS";

//INSCRIPCION
export const LIST_INSCRIPTIONS = "LIST_INSCRIPTIONS";
export const GET_INSCRIPTION = "GET_INSCRIPTION";
export const SAVE_INSCRIPTION = "SAVE_INSCRIPTION";
export const UPDATE_INSCRIPTION = "UPDATE_INSCRIPTION";
export const INSCRIPTION_STATUS_ACTIONS = "INSCRIPTION_STATUS_ACTIONS";