//COMMON
export const FETCH_START = 'fetch_start';
export const FETCH_SUCCESS = 'fetch_success';
export const FETCH_ERROR = 'fetch_error';
export const SHOW_MESSAGE = 'SHOW_MESSAGE';
export const HIDE_MESSAGE = 'HIDE_MESSAGE';

//AUTH
export const SIGNIN_USER = 'SIGNIN_USER';
export const SIGNIN_USER_SUCCESS = 'SIGNIN_USER_SUCCESS';
export const SIGNOUT_USER = 'SIGNOUT_USER';
export const SIGNOUT_USER_SUCCESS = 'SIGNOUT_USER_SUCCESS';
export const INIT_URL = 'INIT_URL';
export const USER_DATA = 'user_data';
export const USER_TOKEN_SET = 'user_token_set';
export const USER_UPDATE_PASSWORD = 'USER_UPDATE_PASSWORD';
export const PASSWORD_REQUIREMENTS = 'PASSWORD_REQUIREMENTS';
export const AUTH_MESSAGE='AUTH_MESSAGE';
export const AUTH_STATUS_ACTIONS='AUTH_STATUS_ACTIONS';

//COLABORADOR
export const LIST_WORKER    = "LIST_WORKER";
export const SAVE_WORKER    = "SAVE_WORKER";
export const WORKER_STATUS_ACTIONS    = "WORKER_STATUS_ACTIONS";
export const ACTIVE_WORKER    = "ACTIVE_WORKER";
export const UPDATE_WORKER    = "UPDATE_WORKER";
export const GET_WORKER    = "GET_WORKER";
export const RESET_PASSWORD_WORKER    = "RESET_PASSWORD_WORKER";
export const FILTER_WORKER    = "FILTER_WORKER";

//ASISTENCIA
export const LIST_ASSISTANCE_BY_WORKER    = "LIST_ASSISTANCE_BY_WORKER";
export const LIST_ASSISTANCE_ALL    = "LIST_ASSISTANCE_ALL";
export const LIST_ASSISTANCE    = "LIST_ASSISTANCE";
export const SAVE_ASSISTANCE    = "SAVE_ASSISTANCE";
export const MY_ASSISTANCE    = "MY_ASSISTANCE";
export const MY_ASSISTANCE_DETAIL    = "MY_ASSISTANCE_DETAIL";
export const INDICATORS_ASSISTANCE    = "INDICATORS_ASSISTANCE";
export const INDICATORS_ASSISTANCE_ALL    = "INDICATORS_ASSISTANCE_ALL";
export const MY_TODAY_ASSISTANCE    = "MY_TODAY_ASSISTANCE";
export const ASSISTANCE_STATUS_ACTIONS    = "ASSISTANCE_STATUS_ACTIONS";
export const SAVE_ASSISTANCE_JUSTIFICATION    = "SAVE_ASSISTANCE_JUSTIFICATION";

//ASOCIADO
export const LIST_ASSOCIATED    = "LIST_ASSOCIATED";
export const FILTER_ASSOCIATED    = "FILTER_ASSOCIATED";
export const INDICATORS_ASSOCIATED    = "INDICATORS_ASSOCIATED";
export const ASSOCIATED_STATUS_ACTIONS    = "ASSOCIATED_STATUS_ACTIONS";

//ASOCIADO
export const FILTER_DEBCOLLECTOR    = "FILTER_DEBCOLLECTOR";

//LLAMADA
export const LIST_CALLS    = "LIST_CALLS";
export const SAVE_CALL    = "SAVE_CALL";
export const CALLS_STATUS_ACTIONS    = "CALLS_STATUS_ACTIONS";