//ASISTENCIA
export const LIST_ASSISTANCE    = "LIST_ASSISTANCE";
export const LIST_MY_ASSISTANCE = "LIST_MY_ASSISTANCE";
export const SAVE_ASSISTANCE    = "SAVE_ASSISTANCE";


export const ADD_ARTICLE = "ADD_ARTICLE";